//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagicSet
    {
        public MagicSet()
        {
            this.Drafts = new HashSet<Draft>();
            this.Drafts1 = new HashSet<Draft>();
            this.Drafts2 = new HashSet<Draft>();
        }
    
        public int SetId { get; set; }
        public string SetName { get; set; }
        public string ExpansionName { get; set; }
        public string SetAbbreviation { get; set; }
    
        public virtual ICollection<Draft> Drafts { get; set; }
        public virtual ICollection<Draft> Drafts1 { get; set; }
        public virtual ICollection<Draft> Drafts2 { get; set; }
    }
}
