//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Drafts = new HashSet<Draft>();
            this.Drafts1 = new HashSet<Draft>();
            this.Drafts2 = new HashSet<Draft>();
            this.Drafts3 = new HashSet<Draft>();
            this.Drafts4 = new HashSet<Draft>();
            this.Drafts5 = new HashSet<Draft>();
            this.Drafts6 = new HashSet<Draft>();
            this.Drafts7 = new HashSet<Draft>();
            this.Drafts8 = new HashSet<Draft>();
            this.Announcements = new HashSet<Announcement>();
        }
    
        public int PlayerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsActive { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Draft> Drafts { get; set; }
        public virtual ICollection<Draft> Drafts1 { get; set; }
        public virtual ICollection<Draft> Drafts2 { get; set; }
        public virtual ICollection<Draft> Drafts3 { get; set; }
        public virtual ICollection<Draft> Drafts4 { get; set; }
        public virtual ICollection<Draft> Drafts5 { get; set; }
        public virtual ICollection<Draft> Drafts6 { get; set; }
        public virtual ICollection<Draft> Drafts7 { get; set; }
        public virtual ICollection<Draft> Drafts8 { get; set; }
        public virtual ICollection<Announcement> Announcements { get; set; }
    }
}
